const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',

    ADD_RENTAL: 'ADD_RENTAL',
    SET_RENTALS : 'SET_RENTALS',
    UPDATE_RENTAL_STATUS : 'UPDATE_RENTAL_STATUS',
    REMOVE_RENTAL : "REMOVE_RENTAL",
    GET_ALL_RENTALS : "GET_ALL_RENTALS",
    
    ADD_HOUSE_TYPE : 'ADD_HOUSE_TYPE',
    SET_HOUSE_TYPES : 'SET_HOUSE_TYPES',
    UPDATE_HOUSE_TYPE: "UPDATE_HOUSE_TYPE",
    REMOVE_HOUSE_TYPE: "REMOVE_HOUSE_TYPE",

    GET_ONE_USER: 'GET_ONE_USER',

    ADD_RENTAL_CONTRACT : "ADD_RENTAL_CONTRACT",
    GET_RENTAL_CONTRACT : "GET_RENTAL_CONTRACT",
    DELETE_RENTAL_CONTRACT : "DELETE_RENTAL_CONTRACT",
}

export default actionTypes;